# Generated by Django 4.1.2 on 2022-11-12 18:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
