# Generated by Django 4.1.2 on 2022-10-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vahiculo',
            new_name='Vehiculo',
        ),
    ]
